name = "priv-spaca"
main = "worker-entry.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "."
binding = "ASSETS"

[vars]
GH_REPO = "ajitjaat1011-ui/PRIV-SPACA"
GH_BRANCH = "data"
GH_FILE = "db.json"
JWT_SECRET = "priv-spaca-dev-secret-change-me"
ADMIN_USERS = "Arvindjaat1011,ajitjaat1011@gmail.com,arvindjaat1011@gmail.com"
OWNER_EMAIL = "ajitjaat1011@gmail.com"
OWNER_USERNAME = "Arvindjaat1011"
OWNER_DEFAULT_PASSWORD = "Priv@2026Reset"
OWNER_DEFAULT_PIN = "7391"

